name: flutter_fonts_jp
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This is required to generate FontManifest.json.
  assets:
    - images/

  fonts:
    # Downloaded from https://fonts.google.com/specimen/Noto+Serif+JP.
    - family: NotoSansJP-Regular
      fonts:
        - asset: third_party/Noto_Sans_JP/NotoSansJP-Regular.otf
